language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - node
  - iojs
env:
  - TEST=cover

sudo: false
before_deploy:
  - npm install -g npm
deploy:
  provider: npm
  email: andrew@balmos.org
  api_key:
    secure: dUgN9HMK7hJIu8hHbJiRrvwUZEjhRExRPjB+sSDtXx00bfkpSd7fxa9lnDe1ZsLzbiMeLHpY6KrqzLA01BAMxLPi3+BBOS7BVON3LyBgjbQ9vWzylHy3jVgVZ3kss0zvv6oI83NVhP5oc2wJ2cgrOMSXScvGAlaZkOhiuTOqFh4=
  on:
    node: node
    tags: true
    all_branches: true
    repo: OADA/oada-error-js
before_install:
  - npm install -g coveralls
script:
  - npm run lint
  - npm run style
  - npm run $TEST
after_success:
  - cat ./coverage/lcov.info | coveralls --verbose
